version: '3.3'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always  

  backend:
    image: danilashishkin/foodgram_backend:latest
    volumes:
      - ../static/:/app/static/
      - ../media/:/app/media/food/
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always

  frontend:
    image: danilashishkin/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../static/:/var/html/static/
      - ../media/:/var/html/media/food/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  postgres_data:
  static_value:
  media_value:
